server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyg
    username: root
    password:

thymeleaf:
    cache: false # 关闭页面缓存
    suffix: .html # 构建url时附加到查看的名称后缀
    prefix: classpath:/templates/ #页面映射路径

mybatis:
  type-aliases-package: springboot_maven.pojo #别名
  mapper-locations: classpath:/mybatis/*.xml   #xml文件路径




